#Encrypts text, run pip install cryptography
from cryptography.fernet import Fernet


'''
def write_key():
    key = Fernet.generate_key()
    # create file key.key in wb mode as key_file, then write in key generated by Fernet
    with open("key.key", "wb") as key_file:
        key_file.write(key)'''


def load_key():
    #opening file in rb mode
    file = open("key.key", "rb")
    #read file, then close file and then return the key
    key = file.read()
    file.close()
    return key




key = load_key() 
fer = Fernet(key)


#Only read existing file
def view():
    with open("passwords.txt", 'r') as f:
        for line in f.readlines():
            #Could just do print(line), however, rstrip removes \n and data.split removes pipe operator, assuming pwd doesnt contain any
            data = line.rstrip()
            user, passw = data.split("|")
            print(f"User: {user} | Password: {fer.decrypt(passw.encode()).decode()}")

def add():
    name = input("Account Name: ")
    pwd =  input("Password: ")
    #open file in a mode , w will clear entire file and make a new one, r will read the file cant edit or destroy file, a mode append mode allows to add to end of existing file or create new file if that file does not exist
    with open("passwords.txt", 'a') as f:
        f.write(name + '|' + fer.encrypt(pwd.encode()).decode() + "\n")

while True:
    mode = input("Would you like to add a new password or view existing ones? (view, add)?, press q to quit  ").lower()
    if mode =='q':
        break

    if mode == 'view':
        view()
    elif mode == 'add':
        add()
    else:
        print("Invalid mode.")
        #brings them to top of while loop
        continue